### ISSUE TITLE
Error msg when editing an event page

### ISSUE THREAD

**Issue by tliacas** [LeHubca/lehub-website#13]
Tried editing this page and adding a start date: 
https://www.lehub.ca/admin/#/collections/events/entries/2024-07-04-hub_extreme_weather_events_microgrant_program

Got this msg by email:

<img width="861" alt="Screenshot 2024-07-25 at 1 28 46 PM" src="https://github.com/user-attachments/assets/d09e512a-5d7a-46bd-8268-f6c2980988b1">

**Comment by alberto56** [comment]
Based on https://github.com/LeHubca/lehub-website/commits/master/, it seems that you made a new change while the site was being built for a previous change, this is not a problem.

![Screenshot 2024-07-25 at 13 49 41](https://github.com/user-attachments/assets/e823ef74-173a-4eb9-8ef3-024333049eb1)

Let me know if any any change you made is not showing up on the site.
