### ISSUE TITLE
Broken link 

### ISSUE THREAD

**Issue by jacquelineleetam** [LeHubca/lehub-website#9]
Hey Albert - 

We caught a broken link on this page: https://www.lehub.ca/en/offerings/

(I think I did something funky to it a couple months ago but I'd rather not risk messing it up again)

[Sign up to access full info on upcoming workshops and registration links.] should be linked to this: https://www.lehub.ca/en/#inscription

Thanks!

**Comment by alberto56** [comment]
Hi @jacquelineleetam I went to https://www.lehub.ca/admin, then went to Secondary Pages, then edited "Offerings". The link is set to "https://github.com/LeHubca/lehub-website/blob/7ae839a7ca70bb0a326d9eb6d14edbe4765898ef/docs/_posts/2021-11-18-map_layout_secondary2021_hideform_false_lang_en_secondary_page_title_offerings_permalink_en_offerings-beta2_body_1-_tailored_workshops_and_coaching_sessions_n_ndrawing_on_the_knowledge_of_trusted_movement_practition.md#inscription"

This is an internal GitHub link to edit the page, I simply changed it to https://www.lehub.ca/en/#inscription, then I waited 5 minutes and now it works at https://www.lehub.ca/en/offerings/

![Screenshot 2023-04-04 at 5 43 13 PM](https://user-images.githubusercontent.com/808265/229929487-927ef18f-8fe8-423b-a2e5-e8a557e253c9.jpg)
![Screenshot 2023-04-04 at 5 43 25 PM](https://user-images.githubusercontent.com/808265/229929490-d472abb4-eba4-44af-b27b-e5901cd40877.jpg)
